packages:
  - "packages/*"
  - "backend/*"
  - "apps/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  protobufjs: true
  '@firebase/util': true
minimumReleaseAgeExclude:
  - '@expo/cli@56.1.18'
  - '@expo/config-plugins@56.0.11'
  - '@expo/config@56.0.11'
  - '@expo/env@2.3.1'
  - '@expo/fingerprint@0.19.6'
  - '@expo/image-utils@0.10.2'
  - '@expo/inline-modules@0.0.13'
  - '@expo/local-build-cache-provider@56.0.9'
  - '@expo/metro-config@56.0.16'
  - '@expo/prebuild-config@56.0.18'
  - '@expo/require-utils@56.1.4'
  - '@expo/schema-utils@56.0.2'
  - expo-constants@56.0.20
  - expo-modules-autolinking@56.0.18
  - expo-modules-core@56.0.19
  - expo-modules-jsi@56.0.11
  - expo@56.0.14
  - '@expo/ui@56.0.20'
  - expo-linking@56.0.15
  - expo-router@56.2.13
  - expo-splash-screen@56.0.12
